### ISSUE TITLE
NullPointerException when map/reduce is not involved on tables with partitions

### ISSUE THREAD

**Issue by sztanko** [rcongiu/Hive-JSON-Serde#106]
Hello, thank you for your work!

I have hive 1.1.0, running on hadoop 1.2

On a table with partitions, whenever I try to do a simple query which tells hive not to execute mapreduce but just read data straight from hdfs, it raises an exception:
```
create external table jsonbug(
a int,
b string
)
    PARTITIONED BY (
    `c` string)
ROW FORMAT SERDE
  'org.openx.data.jsonserde.JsonSerDe'
WITH SERDEPROPERTIES (
      'ignore.malformed.json'='true')
STORED AS INPUTFORMAT
  'org.apache.hadoop.mapred.TextInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  '/tmp/jsonbug';

ALTER TABLE jsonbug ADD PARTITION(c='1');

select * from jsonbug;

```
This raises the following error:
```
=> select * from jsonbug;
FAILED: RuntimeException org.apache.hadoop.hive.ql.metadata.HiveException: Failed with exception nulljava.lang.NullPointerException
	at org.apache.hadoop.hive.ql.exec.FetchOperator.needConversion(FetchOperator.java:607)
	at org.apache.hadoop.hive.ql.exec.FetchOperator.setupOutputObjectInspector(FetchOperator.java:578)
	at org.apache.hadoop.hive.ql.exec.FetchOperator.initialize(FetchOperator.java:172)
	at org.apache.hadoop.hive.ql.exec.FetchOperator.<init>(FetchOperator.java:140)
	at org.apache.hadoop.hive.ql.exec.FetchTask.initialize(FetchTask.java:79)
	at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:455)
	at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:307)
	at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1112)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1160)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1049)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1039)
	at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:207)
	at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:159)
	at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:370)
	at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:754)
	at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:675)
	at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:615)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:160)

```
It works fine if I execute a query involving map/reduce job though: 
```
=> select c, count(1) from jsonbug group by c;
Query ID = sztanko_20150420135252_edadf647-6115-4592-9665-6d145c7781c0
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks not specified. Estimated from input data size: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapred.reduce.tasks=<number>
Starting Job = job_201503171407_5506, Tracking URL = http://namenode:50030/jobdetails.jsp?jobid=job_201503171407_5506
Kill Command = /local/hadoop/libexec/../bin/hadoop job  -kill job_201503171407_5506
Hadoop job information for Stage-1: number of mappers: 1; number of reducers: 1
2015-04-20 13:52:16,478 Stage-1 map = 0%,  reduce = 0%
2015-04-20 13:52:21,498 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 1.09 sec
2015-04-20 13:52:31,540 Stage-1 map = 100%,  reduce = 33%, Cumulative CPU 1.09 sec
2015-04-20 13:52:33,548 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 2.88 sec
MapReduce Total cumulative CPU time: 2 seconds 880 msec
Ended Job = job_201503171407_5506
MapReduce Jobs Launched:
Stage-Stage-1: Map: 1  Reduce: 1   Cumulative CPU: 2.88 sec   HDFS Read: 7106 HDFS Write: 4 SUCCESS
Total MapReduce CPU Time Spent: 2 seconds 880 msec
OK
c	_c1
1	1
Time taken: 36.082 seconds, Fetched: 1 row(s)
```

### How the serde was compiled and installed

```
git clone git@github.com:rcongiu/Hive-JSON-Serde.git
cd Hive-JSON-Serde/
mvn -Pcdh5 -Dcdh5.hive.version=1.1.0 clean package
scp json-serde/target/json-serde-1.3.1-SNAPSHOT-jar-with-dependencies.jar target_server:~/
```

### Data
Content of /tmp/jsonbug/c=1/a1.json
```
{"a": 1, "b": "test"}
```

**Comment by rcongiu** [comment]
Mmm...the exception is not in the serde code, which makes it hard to figure out. Have you tried a newer version of hive ?
I'll look into it anyhow, thanks for the detailed report by the way!R. -------------------------------------------------------
"Good judgment comes from experience. 
Experience comes from bad judgment"
------------------------------------------------------- 


     On Monday, April 20, 2015 6:54 AM, Demeter Sztanko <notifications@github.com> wrote:
   

 Hello, thank you for your work!I have hive 1.1.0, running on hadoop 1.2On a table with partitions, whenever I try to do a simple query which tells hive not to execute mapreduce but just read data straight from hdfs, it raises an exception:create external table jsonbug(
a int,
b string
)
    PARTITIONED BY (
    `c` string)
ROW FORMAT SERDE
  'org.openx.data.jsonserde.JsonSerDe'
WITH SERDEPROPERTIES (
      'ignore.malformed.json'='true')
STORED AS INPUTFORMAT
  'org.apache.hadoop.mapred.TextInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  '/tmp/jsonbug';

ALTER TABLE jsonbug ADD PARTITION(c='1');

select * from jsonbug;

This raises the following error:=> select * from jsonbug;
FAILED: RuntimeException org.apache.hadoop.hive.ql.metadata.HiveException: Failed with exception nulljava.lang.NullPointerException
    at org.apache.hadoop.hive.ql.exec.FetchOperator.needConversion(FetchOperator.java:607)
    at org.apache.hadoop.hive.ql.exec.FetchOperator.setupOutputObjectInspector(FetchOperator.java:578)
    at org.apache.hadoop.hive.ql.exec.FetchOperator.initialize(FetchOperator.java:172)
    at org.apache.hadoop.hive.ql.exec.FetchOperator.<init>(FetchOperator.java:140)
    at org.apache.hadoop.hive.ql.exec.FetchTask.initialize(FetchTask.java:79)
    at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:455)
    at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:307)
    at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1112)
    at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1160)
    at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1049)
    at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1039)
    at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:207)
    at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:159)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:370)
    at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:754)
    at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:675)
    at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:615)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:160)

It works fine if I execute a query involving map/reduce job though: => select c, count(1) from jsonbug group by c;
Query ID = dsztanko_20150420135252_edadf647-6115-4592-9665-6d145c7781c0
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks not specified. Estimated from input data size: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapred.reduce.tasks=<number>
Starting Job = job_201503171407_5506, Tracking URL = http://bihadoop1.mlan:50030/jobdetails.jsp?jobid=job_201503171407_5506
Kill Command = /local/hadoop/libexec/../bin/hadoop job  -kill job_201503171407_5506
Hadoop job information for Stage-1: number of mappers: 1; number of reducers: 1
2015-04-20 13:52:16,478 Stage-1 map = 0%,  reduce = 0%
2015-04-20 13:52:21,498 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 1.09 sec
2015-04-20 13:52:31,540 Stage-1 map = 100%,  reduce = 33%, Cumulative CPU 1.09 sec
2015-04-20 13:52:33,548 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 2.88 sec
MapReduce Total cumulative CPU time: 2 seconds 880 msec
Ended Job = job_201503171407_5506
MapReduce Jobs Launched:
Stage-Stage-1: Map: 1  Reduce: 1   Cumulative CPU: 2.88 sec   HDFS Read: 7106 HDFS Write: 4 SUCCESS
Total MapReduce CPU Time Spent: 2 seconds 880 msec
OK
c   _c1
1   1
Time taken: 36.082 seconds, Fetched: 1 row(s)

Additional information

How the serde was compiled and installed
git clone git@github.com:rcongiu/Hive-JSON-Serde.git
cd Hive-JSON-Serde/
mvn -Pcdh5 -Dcdh5.hive.version=1.1.0 clean package
scp json-serde/target/json-serde-1.3.1-SNAPSHOT-jar-with-dependencies.jar target_server:~/

Data
Content of /tmp/jsonbug/c=1/a1.json{"a": 1, "b": test}

**Comment by sztanko** [comment]
It looks like it is failing because it tries to get the annotation of the SerDe:
```
Class<?> tableSerDe = tableDesc.getDeserializerClass();
    String[] schemaProps = AnnotationUtils.getAnnotation(tableSerDe, SerDeSpec.class).schemaProps();
```
Now, This annotation of class SerDeSpec is something totally new in Hive 1.1 That's the main reason it breaks. Looks like HIVE-7977 made the code backwards incompatible.

**Comment by sztanko** [comment]
AFAIK, Hive 1.0 is the latest version:)

**Comment by sztanko** [comment]
It looks like adding a simple annotation solves the problem:
```
@SerDeSpec(schemaProps={serdeConstants.LIST_COLUMNS, serdeConstants.LIST_COLUMN_TYPES})
public class JsonSerDe extends AbstractSerDe {
```

However SerDeSpec depends on hive 1.1 libraries and it makes the code backwards incompatible.
One solution could be to write a 1.1 shim that will be defining a wrapper around original JsonSerDe with annotation added.
I am happy to make necessary patches myself, just tell me how would you prefer me to do that.

**Comment by rcongiu** [comment]
mm, that will require have 2 copies of the serde file... I think this should be fixed on hive and I am surprised it does not affect other serdes...
it seems an easy enough fix on hive side (check if there's an annotation...it's a pretty elementary bug), can you file a bug report on hive with your findings ?I can do it but it's you who actually found the bug and I don't want to take your credit :D -------------------------------------------------------
"Good judgment comes from experience. 
Experience comes from bad judgment"
------------------------------------------------------- 


     On Tuesday, April 21, 2015 3:56 AM, Demeter Sztanko <notifications@github.com> wrote:
   

 It looks like adding a simple annotation solves the problem:@SerDeSpec(schemaProps={serdeConstants.LIST_COLUMNS, serdeConstants.LIST_COLUMN_TYPES})
public class JsonSerDe extends AbstractSerDe {
However SerDeSpec depends on hive 1.1 libraries and it makes the code backwards incompatible.
One solution could be to write a 1.1 shim that will be defining a wrapper around original JsonSerDe with annotation added.
I am happy to make necessary patches myself, just tell me how would you prefer me to do that.—

**Comment by sztanko** [comment]
I see what you mean. In fact, I tried other json serde's and they don't work neither, so it affects all of them:)

I will raise a ticket on HIve side, will see how it goes there. Thanks:)

**Comment by rcongiu** [comment]
Yeah, the workaround is pretty complicated, and since it affects other serdes, and since it should be an easy fix, we'd end up complicating the hive serde for an issue that will most likely be fixed :DLet me know if I can help - I can vote the issue up for instance. -------------------------------------------------------
"Good judgment comes from experience. 
Experience comes from bad judgment"
------------------------------------------------------- 


     On Tuesday, April 21, 2015 10:06 AM, Demeter Sztanko <notifications@github.com> wrote:
   

 I see what you mean. In fact, I tried other json serde's and they don't work neither, so it affects all of them:)I will raise a ticket on HIve side, will see how it goes there. Thanks:)—

**Comment by sztanko** [comment]
Created a ticket with description: https://issues.apache.org/jira/browse/HIVE-10437

Thanks once again Reoberto for your amazing library and support you offer:)
