### ISSUE TITLE
org.apache.hadoop.io.DoubleWritable cannot be cast to org.apache.hadoop.hive.serde2.io.DoubleWritable

### ISSUE THREAD

**Issue by xelllee** [rcongiu/Hive-JSON-Serde#56]
Still have this issue with casting.

org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.ClassCastException: org.apache.hadoop.io.DoubleWritable cannot be cast to org.apache.hadoop.hive.serde2.io.DoubleWritable
    at org.apache.hadoop.hive.ql.exec.GroupByOperator.closeOp(GroupByOperator.java:1132)
    at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:558)
    at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:567)
    at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:567)
    at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:567)
    at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:567)
    at org.apache.hadoop.hive.ql.exec.ExecMapper.close(ExecMapper.java:191)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:57)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:417)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:332)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:268)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1408)
    at org.apache.hadoop.mapred.Child.main(Child.java:262)
Caused by: java.lang.ClassCastException: org.apache.hadoop.io.DoubleWritable cannot be cast to org.apache.hadoop.hive.serde2.io.DoubleWritable
    at org.apache.hadoop.hive.serde2.objectinspector.primitive.WritableDoubleObjectInspector.get(WritableDoubleObjectInspector.java:35)
    at org.apache.hadoop.hive.serde2.objectinspector.ObjectInspectorUtils.hashCode(ObjectInspectorUtils.java:454)
    at org.apache.hadoop.hive.ql.exec.ReduceSinkOperator.processOp(ReduceSinkOperator.java:226)
    at org.apache.hadoop.hive.ql.exec.Operator.process(Operator.java:474)
    at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:800)
    at org.apache.hadoop.hive.ql.exec.GroupByOperator.forward(GroupByOperator.java:1061)
    at org.apache.hadoop.hive.ql.exec.GroupByOperator.closeOp(GroupByOperator.java:1113)
    ... 14 more
org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.ClassCastException: org.apache.hadoop.io.DoubleWritable cannot be cast to org.apache.hadoop.hive.serde2.io.DoubleWritable
    at org.apache.hadoop.hive.ql.exec.GroupByOperator.closeOp(GroupByOperator.java:1132)
    at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:558)
    at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:567)
    at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:567)
    at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:567)
    at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:567)
    at org.apache.hadoop.hive.ql.exec.ExecMapper.close(ExecMapper.java:191)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:57)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:417)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:332)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:268)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1408)
    at org.apache.hadoop.mapred.Child.main(Child.java:262)
Caused by: java.lang.ClassCastException: org.apache.hadoop.io.DoubleWritable cannot be cast to org.apache.hadoop.hive.serde2.io.DoubleWritable
    at org.apache.hadoop.hive.serde2.objectinspector.primitive.WritableDoubleObjectInspector.get(WritableDoubleObjectInspector.java:35)
    at org.apache.hadoop.hive.serde2.objectinspector.ObjectInspectorUtils.hashCode(ObjectInspectorUtils.java:454)
    at org.apache.hadoop.hive.ql.exec.ReduceSinkOperator.processOp(ReduceSinkOperator.java:226)
    at org.apache.hadoop.hive.ql.exec.Operator.process(Operator.java:474)
    at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:800)
    at org.apache.hadoop.hive.ql.exec.GroupByOperator.forward(GroupByOperator.java:1061)
    at org.apache.hadoop.hive.ql.exec.GroupByOperator.closeOp(GroupByOperator.java:1113)
    ... 14 more

**Comment by ovlaere** [comment]
I'm facing a similar issue, getting the `java.lang.ClassCastException: org.apache.hadoop.io.DoubleWritable cannot be cast to org.apache.hadoop.hive.serde2.io.DoubleWritable`. 

I am comparing double values from a table using JSON serde to other double values computed from `percentile_approx`, and even though both are double, there is a ClassCastException.

Reading the comment by @rcongiu about bypassing the objectinspector, I managed to get the computation to complete, by disabling the automapjoin (`set hive.auto.convert.join=false;`). In that case, everything works. So clearly, when optimizing for map-joins, things are being bypassed.

Hope this helps in identifying the cause of this Exception,

**Comment by vahnj** [comment]
Hi-

I've figured out what's causing this problem, and it's related to how you're serializing primitives.

[I've submitted a pull request that has solved this problem for me](https://github.com/rcongiu/Hive-JSON-Serde/pull/160).  Let me know if you have any questions.

-James

**Comment by rcongiu** [comment]
That is a sub-optimal fix though, as it will create a lot of extra objects, which will impact performance/garbage collection. So it does fix one particular bug, but then makes things slightly worse all the time.

**Comment by vahnj** [comment]
Yeah, that's fair.  I mostly was just digging through this after encountering an issue today caused by joins with this and wanted to throw together a quick fix & share what the problem actually seemed to be.
