### ISSUE TITLE
get_json_object on Json String does not work with Serde

### ISSUE THREAD

**Issue by snehalNagmote** [rcongiu/Hive-JSON-Serde#70]
My sample table definition is as follows
create external table if not exists test (
ctx          string,
test int
)PARTITIONED BY (game_id STRING)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe';

Input data:
{"ctx":{"reason":184,"initial":105,"name":62,"delta":5}, "test":123,"game_id":"xxx"}

I want to  avoid creating struct for every json string , so I am using string for ctx instead of struct , When I query ctx using get_json_object ,

select get_json_object(ctx,'$.reason') from test where game_id='xxx';  

I get following exception 

Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Unable to execute method public org.apache.hadoop.io.Text org.apache.hadoop.hive.ql.udf.UDFJson.evaluate(java.lang.String,java.lang.String)  on object org.apache.hadoop.hive.ql.udf.UDFJson@662d167e of class org.apache.hadoop.hive.ql.udf.UDFJson with arguments {{"reason":"184","initial":"105","delta":"5","name":"62"}:org.openx.data.jsonserde.json.JSONObject, $.reason:java.lang.String} of size 2
    at org.apache.hadoop.hive.ql.exec.FunctionRegistry.invoke(FunctionRegistry.java:1241)
    at org.apache.hadoop.hive.ql.udf.generic.GenericUDFBridge.evaluate(GenericUDFBridge.java:182)
    at org.apache.hadoop.hive.ql.exec.ExprNodeGenericFuncEvaluator._evaluate(ExprNodeGenericFuncEvaluator.java:166)
    at org.apache.hadoop.hive.ql.exec.ExprNodeEvaluator.evaluate(ExprNodeEvaluator.java:77)
    at org.apache.hadoop.hive.ql.exec.ExprNodeEvaluator.evaluate(ExprNodeEvaluator.java:65)
    at org.apache.hadoop.hive.ql.exec.SelectOperator.processOp(SelectOperator.java:79)
    at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:793)
    at org.apache.hadoop.hive.ql.exec.TableScanOperator.processOp(TableScanOperator.java:92)
    at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:793)
    at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:540)
    ... 9 more
Caused by: java.lang.IllegalArgumentException: argument type mismatch
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.hive.ql.exec.FunctionRegistry.invoke(FunctionRegistry.java:1217)
    ... 18 more

It converts string to org.openx.data.jsonserde.json.JSONObject .

Any pointers why it does not work  or why/where the conversion happen?

**Comment by furmangg** [comment]
I didn't have any luck with the cast workaround for get_json_object. But "lateral view json_tuple" seems to be working.
